services:
  agent:
    build: .
    container_name: agent
    devices:
      - /dev/gpiomem:/dev/gpiomem
    privileged: true
    cap_add:
      - SYS_RAWIO
    environment:
      XMPP_SERVER: "prosody"
      XMPP_PORT: 5222
      XMPP_DOMAIN: "prosody"
      XMPP_USERNAME: "alpha-pi-4b-agent"
      XMPP_PASSWORD: "top_secret"
      PYTHONUNBUFFERED: 1
    volumes:
      - ./agent:/agent
    extra_hosts:
      - "prosody:192.168.237.60"
