services:
  alphabot_agent:
    build: ./alphabot_agent/
    container_name: alphabot_agent
    devices:
      - /dev/gpiomem:/dev/gpiomem
    privileged: true
    cap_add:
      - SYS_RAWIO
    environment:
      XMPP_SERVER: "prosody"
      XMPP_PORT: 5222
      XMPP_DOMAIN: "prosody"
      XMPP_USERNAME: "alpha-pi-4b-agent"
      XMPP_PASSWORD: "top_secret"
      PYTHONUNBUFFERED: 1
    volumes:
      - ./alphabot_agent:/alphabot_agent
    extra_hosts:
      - "prosody:${PROSODY_IP}"
  calibration_agent:
    build: ./calibration_agent/
    container_name: calibration_agent
    environment:
      XMPP_SERVER: "prosody"
      XMPP_PORT: 5222
      XMPP_DOMAIN: "prosody"
      XMPP_USERNAME: "calibration_agent"
      XMPP_PASSWORD: "top_secret"
      PYTHONUNBUFFERED: 1
    volumes:
      - ./calibration_agent:/app/src
    privileged: true
    extra_hosts:
      - "prosody:${PROSODY_IP}"
